language: node_js

notifications:
    email:
        - yiminghe@gmail.com

node_js:
  - 16.13.1

before_install:
  - corepack enable

install:
  - yarn run bootstrap

script:
  - yarn check
  - yarn start &
  - yarn cypress run --record --key 7ee3b205-230d-40e6-88ff-ddcadb1095a0
  - kill $(jobs -p) || true